name:    clap-counter
version: "0.0.1"

dependencies:
- base
- scotty
- stm
- aeson
- blaze-builder
- bytestring
- case-insensitive
- data-default-class
- exceptions
- fail
- http-types
- monad-control
- mtl
- nats
- network
- regex-compat
- text
- transformers
- transformers-base
- transformers-compat
- wai
- wai-extra
- warp

# Runnable executable for our application
executables:
  clap-counter:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall -O2 -static -threaded
    cc-options: -static
    ld-options: -static -pthread
    extra-lib-dirs:
      - /usr/lib/musl/ # libc static
      - lib/ # gmp static
