name:    clap-counter
version: "0.0.0"

dependencies:
- base
- yesod-core

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  clap-counter:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall -O2 -static -threaded
    cc-options: -static
    ld-options: -static -pthread
    extra-lib-dirs:
      - /usr/lib/musl/ # libc static
      - lib/ # gmp static
    dependencies:
    - clap-counter
